// <auto-generated />
using System;
using JourneyMicroservice.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace JourneyMicroservice.EntityFramework.Migrations
{
    [DbContext(typeof(JourneyContext))]
    partial class JourneyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.15");

            modelBuilder.Entity("JourneyMicroservice.Core.Entity.Journey", b =>
                {
                    b.Property<int>("IdJourney")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Arrival")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("Departure")
                        .HasColumnType("datetime");

                    b.Property<int>("Destination")
                        .HasColumnType("int");

                    b.Property<int>("Origin")
                        .HasColumnType("int");

                    b.HasKey("IdJourney");

                    b.ToTable("Journeys");
                });
#pragma warning restore 612, 618
        }
    }
}
