version: '3.4'
volumes:
  journey-datafiles:
  passenger-datafiles:
  ticket-datafiles:
  logs-datafiles:

    #Journey Microservice
services:
  journeymicroservice:
    image: ${DOCKER_REGISTRY-}journeymicroservice
    build:
      context: .
      dockerfile: JourneyMicroservice.Api/Dockerfile
    depends_on: 
            - journey-database
    ports:
          - "5014:80"
          - "732:443"
    restart: always
        
    environment: 
          - Journey-database
          - ASPNETCORE_ENVIRONMENT=Development

    #Passenger  Microservice
  passengermicroservice:
    image: ${DOCKER_REGISTRY-}passengermicroservice
    build:
      context: .
      dockerfile: PassengerMicroservice.Api/Dockerfile
    depends_on: 
            - passenger-database
    ports:
          - "5015:80"
          - "733:443"
    restart: always
        
    environment: 
          - Passenger-database
          - ASPNETCORE_ENVIRONMENT=Development
    #Ticket  Microservice
  ticketmicroservice:
    image: ${DOCKER_REGISTRY-}ticketmicroservice
    build:
      context: .
      dockerfile: TicketMicroservice.Api/Dockerfile
    depends_on: 
            - ticket-database
    ports:
          - "5016:80"
          - "734:443"
    restart: always
        
    environment: 
          - Ticket-database
          - ASPNETCORE_ENVIRONMENT=Development

#Db Journey
  journey-database:
        image: mysql:8.0.25
        ports:
          - "3366:3306"
        volumes:
          - journey-datafiles:/var/lib/mysql
        restart: always
        environment: 
          MYSQL_ROOT_PASSWORD: root
          MYSQL_USER: emanueld92
          MYSQL_PASSWORD: password
          MYSQL_DATABASE: journey

#Db Passenger
  passenger-database:
        image: mysql:8.0.25
        ports:
          - "3367:3306"
        volumes:
          - passenger-datafiles:/var/lib/mysql
        restart: always
        environment: 
          MYSQL_ROOT_PASSWORD: root
          MYSQL_USER: emanueld92
          MYSQL_PASSWORD: password
          MYSQL_DATABASE: passenger
#Db Ticket
  ticket-database:
        image: mysql:8.0.25
        ports:
          - "3368:3306"
        volumes:
          - ticket-datafiles:/var/lib/mysql
        restart: always
        environment: 
          MYSQL_ROOT_PASSWORD: root
          MYSQL_USER: emanueld92
          MYSQL_PASSWORD: password
          MYSQL_DATABASE: ticket
#DB Logs
  logs-database:
        image: mysql:8.0.25
        ports:
          - "3390:3306"
        volumes:
          - logs-datafiles:/var/lib/mysql
        restart: always
        environment: 
          MYSQL_ROOT_PASSWORD: root
          MYSQL_USER: rootPW
          MYSQL_PASSWORD: vero
          MYSQL_DATABASE: logs